server:
  port: 8080
  allowOrigins:
    - "*"
  bodyLimit: "10M" # MiB
  timeout: 30 # Seconds

database:
  host: localhost
  port: 5432
  user: postgres
  password: 123456
  dbname: kioskmachinedb
  sslmode: disable
  schema: public
